version: '3.7'

# >>> SERVICES >>>
services:

  # >>> Weather React App >>>
  weather_react:
    image: react/weather-react:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: weather_react
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - react-network
  # <<< Weather React App <<<

# >>> NETWORKS >>>
networks:
  react-network:
    driver: bridge
